version: '2'
services:
    testify-app:
        image: testify
        external_links:
            - testify-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testify?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testify-mysql:
        extends:
            file: mysql.yml
            service: testify-mysql
